import HTML from '../assets/HTML5.svg'
import Photoshop from '../assets/adobe_photoshop.svg'
import Chatgpt from '../assets/chatGPT.png'
import CSS from '../assets/CSS3.svg'
import Figma from '../assets/figma_logo.png'
import Git from '../assets/git_logo.png'
import Github from '../assets/github.png'
import HeroImage from '../assets/hero_image.png'
import Javascript from '../assets/JavaScript.png'
import Linkedin from '../assets/linkedin.png'
import Netlify from '../assets/netlify.png'
import Project1 from '../assets/Project_1.png'
import Project2 from '../assets/Project_2.png'
import Project3 from '../assets/Project_3.png'
import Project4 from '../assets/Project_4.png'
import Project5 from '../assets/Project_5.png'
import ReactLogo from '../assets/React.svg'
import TailwindLogo from '../assets/tailwind.svg'
import Vscode from '../assets/vscode.png'
import Wordpress from '../assets/WordPress_logo.svg'
import Npm from '../assets/npm.svg'
import Menu from '../assets/menu_24dp.png'
import menuOpen from '../assets/menu_open_24dp.png'

export {HTML, Photoshop, Chatgpt, CSS, Figma, Git, Github, HeroImage, Javascript, Linkedin, Netlify, Project1, Project2, Project3, Project4, Project5, ReactLogo, TailwindLogo, Vscode, Wordpress, Npm, Menu, menuOpen}